# Main configuration file for the SEBA Gardens Website
---
# Site settings
title: 'SEBA Gardens'
description: 'SEBA Community Gardens Website'
logo: "/images/SEBAGardens_logo.png"
baseurl: ''
permalink: pretty

# Pagination
paginate: 8
paginate_path: news/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: News
    url: /news/
  - title: "Governance"
    url: "/governance/"
  - title: "Search"
    url: "/search/"
  - title: <svg width="16" height="16" class="icon icon--twitter" role="img" alt="twitter"><title>"Twitter"</title><use xlink:href="#twitter" fill="CurrentColor"></use></svg>
    url: https://twitter.com/sebagardens
  - title: <svg width="16" height="16" class="icon icon--github" role="img" alt="github"><title>"GitHub"</title><use xlink:href="#github" fill="CurrentColor"></use></svg>
    url: https://github.com/seba-gardens

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "SEBA Gardens Goings-On"
    feature_image: "/images/SEBAGardens_thin_banner.png"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post  # Set the default layout for posts
      feature_image: "/images/SEBAGardens_thin_banner.png"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page  # Set the default layout for pages
      feature_image: "/images/SEBAGardens_thin_banner.png"

# Syntax highlighter for block quotes
highlighter: rouge

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# Set theme
remote_theme: daviddarnes/alembic@main

# try to speed things up
css_inline: true
