# Main configuration file for the SEBA Gardens Website
---
# Site settings
url: 'https://seba-gardens.github.io'
baseurl: ''
title: 'SEBA Gardens'
description: 'SEBA Community Gardens Website'
permalink: pretty
logo: "/images/tomato.png"

# Pagination
paginate: 8
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: News
  url: /news/
- title: "Governance"
  url: "/governance/"

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "SEBA Gardens Goings-On"
    feature_image: "/images/SEBAGardens_thin_banner.png"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      feature_image: "/images/SEBAGardens_thin_banner.png"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      feature_image: "/images/SEBAGardens_thin_banner.png"

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Set theme
remote_theme: daviddarnes/alembic@main

# try to speed things up
css_inline: true
