name: Check lesson and build for all configs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_lesson_and_build_default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install Dependencies
      run: |
        gem install bundler json kramdown kramdown-parser-gfm
        bundle config set path '.vendor/bundle'
        bundle install
    - name: Build Website
      run: |
        make --always-make site
